### ISSUE TITLE
Terminal gives me a lot of errors :( 

### ISSUE THREAD

**Issue by grace-snow** [btholt/intro-to-web-dev-v2#1]
I have a feeling this is a problem with my computer setup, but **could do with advice on what these errors mean / how to fix**... I'm on a windows 10 Pro surfacebook.

I was attempting to follow the start instructions in the docs (I've only just started reading the course, so maybe I'm getting ahead of myself and this is covered in the written material). Here goes... 

After `npm install`, I got a load of security warnings, then this: 
![image](https://user-images.githubusercontent.com/10631991/40050312-fd6463ce-582e-11e8-8869-6cb21dffec62.png)

And when I then tried `npm run develop` I got this:
![image](https://user-images.githubusercontent.com/10631991/40050427-5a2fcbfc-582f-11e8-9608-a99524a5e8cf.png)

Is this because I need to install python on my machine? Or something else?

**Comment by btholt** [comment]
Huh, looks you do need to have Python installed. I didn't know Gatsby required that.

In any case, you don't need to build this repo for the course. This repo is just the website for the course. You can see the [built site here](https://btholt.github.io/intro-to-web-dev-v2/). Does that help?
