### ISSUE TITLE
404s at JS-Project

### ISSUE THREAD

**Issue by Frankcarvajal** [btholt/intro-to-web-dev-v2#13]
After completing the HTML and CSS on my own, and dabbling with the JS, I went to see the solutions to see the differences I may encounter. I discovered that the links lead to GitHub 404s.

Thanks!

![404s](https://user-images.githubusercontent.com/12778639/42359221-6d76a8f0-8095-11e8-966e-d2d5ad0b886d.gif)

**Comment by 1Marc** [comment]
Fixed!
