### ISSUE TITLE
event parameter missing from calculator exercise

### ISSUE THREAD

**Issue by skorasaurus** [btholt/intro-to-web-dev-v2#14]
The calculator exercise does not function properly (input values are not accepted) when using  Firefox because of a missing parameter at [line 90](https://github.com/btholt/intro-to-web-dev-v2/blob/09d844ebfe1304435f7ffd54125880eaa8a882f2/static/calculator.js#L90) in calculator.js 

Without the event parameter, the calculator works as expected in chrome which is an odd behavior that Brian even mentions. At 9:25 of https://frontendmasters.com/courses/web-development-v2/javascript-html-and-css-solution-part-2 that it's not optional. ;) 

PR forthcoming.

**Comment by 1Marc** [comment]
Looks good, thanks! Accepted.
