### ISSUE TITLE
Images src links are broken

### ISSUE THREAD

**Issue by georgeben** [btholt/intro-to-web-dev-v2#40]
In the basic HTML lesson, the url supplied to the src attribute of the image is broken. The image tag looks like `<img src="http://www.placepuppy.net/100/100" alt="an adorable puppy" />`, the image does not display because http://www.placepuppy.net/100/100 is broken.

**Comment by akiltipu** [comment]
Hello, @georgeben Instead of [www.placepuppy.net](www.placepuppy.net) you can use [palcecorgi.com](palcecorgi.com).

**Comment by haticecs** [comment]
Hi, it should supposed to be http://placecorgi.com. 
Like in the example below.
<img src="http://placecorgi.com/500/250" alt="adorable puppy"/>

Hope it helps.
@georgeben
