### ISSUE TITLE
HTML CSS PROJECT LINK NOT FOUND

### ISSUE THREAD

**Issue by EzikeChris** [btholt/intro-to-web-dev-v2#92]
Html & Css project link returns missing. 
![Screenshot from 2022-02-14 14-41-25](https://user-images.githubusercontent.com/57494924/153875387-8489b85b-ec22-4120-89d9-85579a852057.png)

**Comment by 1Marc** [comment]
Fixed! Thanks for letting us know.

**Comment by EzikeChris** [comment]
Welcome.
